name: Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-style:
    name: Run PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.example .env

      - name: Set up PHP
        uses: erkenes/php-cs-fixer-action@main
        with:
          args: '--dry-run --diff -vvv'

      - name: Remove o .env file
        run: rm .env


  phpcs:
    name: Run PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Create .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --ignore-platform-req=ext-mongodb --no-progress --no-suggest --prefer-dist

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Create the phpcs.xml
        run: cp phpcs.xml.dist phpcs.xml

      - name: Create the phpcs.xml
        run: phpcs --config-set installed_paths src/Standards

      - name: Run PHP_CodeSniffer
        run: ~/.composer/vendor/bin/phpcs -n

      - name: Remove o .env file
        run: rm .env